name: Docker Image CI

on: [push]

jobs:
  build-node-server-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build & push container
        run: |
          cd node_server
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
          docker build -t docker.pkg.github.com/aliehteshami7/chess_backend/node_server:latest .
          docker push docker.pkg.github.com/aliehteshami7/chess_backend/node_server:latest
  build-parse-server-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build & push container
        run: |
          cd parse_node
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
          docker build -t docker.pkg.github.com/aliehteshami7/chess_backend/parse_server:latest .
          docker push docker.pkg.github.com/aliehteshami7/chess_backend/parse_server:latest
  test:
    needs: [build-node-server-docker, build-parse-server-docker]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
      - name: Make env
        run: |
          cp .env-sample .env
          cp mongo-init-sample.js mongo-init.js
      - name: Build the docker-compose stack
        run: docker-compose up -d -f docker-compose.prod.yml
      - name: Sleep
        uses: kibertoad/wait-action@1.0.1
        with:
          time: "90s"
      - name: Check running containers
        run: docker ps -a
