name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Make env
        run: |
          cp .env-sample .env
          cp mongo-init-sample.js mongo-init.js
      - name: Build the docker-compose stack
        run: docker-compose up -d
      - name: Sleep
        uses: kibertoad/wait-action@1.0.1
        with:
          time: '90s'
      - name: Check running containers
        run: docker ps -a
