name: Deploy

on: 
  release: 
  workflow_dispatch:

jobs:
  push-to-server:

    runs-on: ubuntu-latest

    steps:
      - name: deploy command
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: echo salam
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
